version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=cove_user
      - MARIADB_DATABASE=cove
  cove:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-cove}
    ports:
      - '8000:8000'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - SYMFONY_DATABASE_HOST=mariadb
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=cove_user
      - SYMFONY_DATABASE_NAME=cove
    volumes:
      - './cove:/app'
    depends_on:
      - mariadb

